function isGraphicsUpdated = updateVisualization(surface_ax,map_ax,map, ...
                             xg,yg,z_heights,...
                             startLocation,...
                             startYawAngle,...                             
                             endLocation,...
                             endYawAngle,...
                             terrain_points_obs,...
                             sharp_rocks_pts,...
                             round_rocks_pts,...
                             ditches_pts,... 
                             rocks_select)

% Function to update all the plots in the mars_rover_app.

% Copyright 2022-2023 The MathWorks, Inc

isGraphicsUpdated = false;
[az,el] = view(surface_ax);
hold(surface_ax,'on')
% Plot Terrain surface plot with obstacles data
p1 = plot3(surface_ax,startLocation(1),startLocation(2),startLocation(3),'s',...
    'MarkerSize',6,'LineWidth',3,'Color',[1 0 1],...
    'MarkerFaceColor',[1 0 1],'DisplayName','StartLocation');

p2 = plot3(surface_ax,endLocation(1),endLocation(2),endLocation(3),'O',...
    'MarkerSize',6,'LineWidth',3,'Color',[ 0 1 0],...
    'MarkerFaceColor',[0 1 0],'DisplayName','GoalLocation');


handles = plotTerrainSurfaceWithObs(surface_ax,xg,yg,z_heights,...
    terrain_points_obs,...
    sharp_rocks_pts,...
    round_rocks_pts,...
    ditches_pts,...
    rocks_select);  

legend(surface_ax,[p1,p2,handles.p1,handles.p3],'Location','northwest')

%legend(surface_ax,'Location','northwest');
hold(surface_ax,'off');

hold(map_ax,'on');
rectangle(map_ax,'Position', [2.5, 5, 32.5, 30],...
  'EdgeColor',[0 0 0], 'LineWidth', 0.5)

% Plot the occupancy map
show(map,'Parent',map_ax,'FastUpdate',1);
map_ax.XLim = [2.5 35];
map_ax.YLim = [5 35];
% Plot the obstacles on the occupancy map
% Plot start and end locations
plot(map_ax,startLocation(1),startLocation(2),'s',...
    'MarkerSize',6,'LineWidth',3,'Color',[1 0 1],...
    'MarkerFaceColor',[1 0 1],'DisplayName','StartLocation');
plot(map_ax,endLocation(1),endLocation(2),'O',...
    'MarkerSize',6,'LineWidth',3,'Color',[ 0 1 0],...
    'MarkerFaceColor',[0 1 0],'DisplayName','GoalLocation');
plotObstaclesOnOccupancyMap(map_ax,xg,yg,...
    terrain_points_obs,...
    sharp_rocks_pts,...
    round_rocks_pts,...
    ditches_pts,...
    rocks_select);

% [Xg, Yg] = ndgrid(xg, yg);
% hold(map_ax,'on')
% [fx,fy] = gradient(z_heights,xg(2)-xg(1),yg(2)-yg(1));
% quiver(map_ax,Xg,Yg,fx,fy,'AutoScaleFactor',2)
% contour(map_ax,Xg,Yg,z_heights)
% hold(map_ax,'off')



plotTransforms(startLocation,eul2quat([0 0 deg2rad(startYawAngle)],'XYZ'),'Parent',map_ax,'FrameSize',6)
plotTransforms(endLocation,eul2quat([0 0 deg2rad(endYawAngle)],'XYZ'),'Parent',map_ax,'FrameSize',6)
view(map_ax,2)
view(surface_ax,[az,el])
hold(map_ax,'off');
drawnow;
isGraphicsUpdated = true;

end